### ISSUE TITLE
Here not embedded with link in docs.

### ISSUE THREAD

**Issue by R3site** [project-error/projecterror.dev#10]
In the NPWD docs if you go from Getting Started > Installation > General Configuration > toggleKey the "here" for a list of available keys isn't actually embedded with any sort of link.

![image](https://user-images.githubusercontent.com/61720260/148706247-4ec2e752-c9ac-4b9c-b212-a04c6e04f318.png)

**Comment by BombayV** [comment]
https://docs.fivem.net/docs/game-references/input-mapper-parameter-ids/keyboard/
